# problem statement 1.1

  Import the csv file of the stock of your choosing using 'pd.read_csv()' function into a dataframe. Shares of a company can be offered in more than one category. The category of a stock is indicated in the ‘Series’ column. If the csv file has data on more than one category, the ‘Date’ column will have repeating values. To avoid repetitions in the date, remove all the rows where 'Series' column is NOT 'EQ'. Analyze and understand each column properly. You'd find the head(), tail() and describe() functions to be immensely useful for exploration. You're free to carry out any other exploration of your own.

In [19]:
import numpy as np 
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import os
import datetime
from functools import partial

In [20]:
df=pd.read_csv(r"C:\Users\Admin-pc\Downloads\aspiration.ai\GOOG.csv")

In [21]:
df

,Date,Close Price,Open Price,High Price,Low Price,Total Traded Quantity
0,"Oct 24, 2019","1,259.11","1,259.11","1,262.90","1,252.35",1.01M
1,"Oct 23, 2019","1,257.63","1,240.21","1,258.04","1,240.21",1.18M
2,"Oct 22, 2019","1,241.20","1,244.48","1,248.73","1,239.85",1.28M
3,"Oct 21, 2019","1,244.28","1,248.70","1,253.51","1,239.99",1.03M
4,"Oct 18, 2019","1,244.41","1,254.69","1,258.11","1,240.14",1.58M
5,"Oct 17, 2019","1,252.80","1,251.40","1,263.75","1,249.87",1.06M
6,"Oct 16, 2019","1,243.00","1,241.81","1,254.19","1,238.53",1.15M
7,"Oct 15, 2019","1,242.24","1,221.50","1,247.12","1,220.92",1.53M
8,"Oct 14, 2019","1,217.77","1,213.89","1,225.88","1,211.88",683.93K
9,"Oct 11, 2019","1,215.71","1,224.03","1,228.75","1,213.64",1.13M
10,"Oct 10, 2019","1,209.47","1,198.60","1,215.62","1,197.86",668.24K
11,"Oct 09, 2019","1,202.40","1,201.33","1,208.46","1,198.12",813.22K
12,"Oct 08, 2019","1,190.13","1,198.77","1,206.87","1,189.48",1.03M
13,"Oct 07, 2019","1,208.25","1,207.00","1,218.91","1,204.36",879.02K
14,"Oct 04, 2019","1,210.96","1,194.29","1,212.46","1,190.97",1.23M
15,"Oct 03, 2019","1,189.43","1,183.34","1,191.00","1,163.14",1.47M
16,"Oct 02, 2019","1,177.92","1,196.50","1,198.76","1,172.63",1.67M
17,"Oct 01, 2019","1,206.00","1,222.49","1,232.86","1,205.55",1.28M
18,"Sep 30, 2019","1,221.14","1,220.60","1,227.40","1,213.42",1.29M
19,"Sep 27, 2019","1,225.95","1,242.83","1,244.99","1,215.20",1.72M
20,"Sep 26, 2019","1,242.29","1,242.14","1,244.67","1,231.82",1.17M
21,"Sep 25, 2019","1,245.94","1,216.01","1,248.02","1,209.20",1.36M
22,"Sep 24, 2019","1,218.33","1,240.00","1,247.11","1,210.64",1.84M
23,"Sep 23, 2019","1,234.69","1,226.57","1,239.68","1,223.78",1.20M
24,"Sep 20, 2019","1,229.84","1,233.64","1,242.80","1,223.58",1.94M
25,"Sep 19, 2019","1,238.75","1,232.32","1,244.34","1,232.31",847.00K
26,"Sep 18, 2019","1,232.65","1,230.24","1,236.24","1,216.47",892.79K
27,"Sep 17, 2019","1,229.88","1,231.63","1,235.00","1,223.35",1.05M
28,"Sep 16, 2019","1,231.63","1,230.44","1,239.02","1,225.19",1.41M
29,"Sep 13, 2019","1,240.03","1,232.11","1,241.05","1,227.08",1.18M
...,...,...,...,...,...,...
473,"Dec 06, 2017","1,032.72","1,016.52","1,039.58","1,015.31",1.44M
474,"Dec 05, 2017","1,019.60","1,010.99","1,036.68","1,002.32",1.95M
475,"Dec 04, 2017","1,011.87","1,027.80","1,031.34","1,009.22",1.94M
476,"Dec 01, 2017","1,025.07","1,030.41","1,037.24","1,016.90",1.89M
477,"Nov 30, 2017","1,036.17","1,039.94","1,044.14","1,030.07",2.25M
478,"Nov 29, 2017","1,037.38","1,056.18","1,058.77","1,029.65",2.79M
479,"Nov 28, 2017","1,063.29","1,073.99","1,080.00","1,054.54",1.82M
480,"Nov 27, 2017","1,072.01","1,058.57","1,073.04","1,054.77",1.77M
481,"Nov 24, 2017","1,056.52","1,054.39","1,060.07","1,051.92",825.37K
482,"Nov 22, 2017","1,051.92","1,051.16","1,055.43","1,047.25",726.90K
483,"Nov 21, 2017","1,050.30","1,040.04","1,050.39","1,039.14",1.11M
484,"Nov 20, 2017","1,034.66","1,036.00","1,038.69","1,032.67",876.32K
485,"Nov 17, 2017","1,035.89","1,049.80","1,051.00","1,033.73",1.34M
486,"Nov 16, 2017","1,048.47","1,038.75","1,051.76","1,038.00",1.19M
487,"Nov 15, 2017","1,036.41","1,035.00","1,039.63","1,030.76",905.26K
488,"Nov 14, 2017","1,041.64","1,037.72","1,042.30","1,029.33",1.05M
489,"Nov 13, 2017","1,041.20","1,040.80","1,048.74","1,039.26",940.72K
490,"Nov 10, 2017","1,044.15","1,043.87","1,046.63","1,041.22",972.13K
491,"Nov 09, 2017","1,047.72","1,048.00","1,050.88","1,035.85",1.79M
492,"Nov 08, 2017","1,058.29","1,050.05","1,062.69","1,047.05",1.21M
493,"Nov 07, 2017","1,052.39","1,049.65","1,053.41","1,043.00",1.31M
494,"Nov 06, 2017","1,042.68","1,049.10","1,052.59","1,042.00",914.75K
495,"Nov 03, 2017","1,049.99","1,042.75","1,050.66","1,037.65",1.39M
496,"Nov 02, 2017","1,042.97","1,039.99","1,045.52","1,028.66",1.33M
497,"Nov 01, 2017","1,042.60","1,036.32","1,047.86","1,034.00",2.16M
498,"Oct 31, 2017","1,033.04","1,033.00","1,041.00","1,026.30",1.52M
499,"Oct 30, 2017","1,033.13","1,029.16","1,039.83","1,022.33",2.34M
500,"Oct 27, 2017","1,033.67","1,030.99","1,063.62","1,026.85",5.18M
501,"Oct 26, 2017",991.42,998.47,"1,006.51",990.47,2.37M
502,"Oct 25, 2017",991.46,986.27,994.43,977.72,1.53M

In [22]:
df['Low Price'] = df['Low Price'].str.replace(',', '')
df['Low Price'] = pd.to_numeric(df['Low Price'])
df['High Price'] = df['High Price'].str.replace(',', '')
df['High Price'] = pd.to_numeric(df['High Price'])
df['Close Price'] = df['Close Price'].str.replace(',', '')
df['Close Price'] = pd.to_numeric(df['Close Price'])
df['Open Price'] = df['Open Price'].str.replace(',', '')
df['Open Price'] = pd.to_numeric(df['Open Price'])

In [23]:
df['Total Traded Quantity']=df['Total Traded Quantity'].replace({'K': '*1e3', 'M': '*1e6'}, regex=True).map(pd.eval).astype(float)

In [24]:
df.head()

,Date,Close Price,Open Price,High Price,Low Price,Total Traded Quantity
0,"Oct 24, 2019",1259.11,1259.11,1262.90,1252.35,1010000.0
1,"Oct 23, 2019",1257.63,1240.21,1258.04,1240.21,1180000.0
2,"Oct 22, 2019",1241.20,1244.48,1248.73,1239.85,1280000.0
3,"Oct 21, 2019",1244.28,1248.70,1253.51,1239.99,1030000.0
4,"Oct 18, 2019",1244.41,1254.69,1258.11,1240.14,1580000.0

In [25]:
df.tail()

,Date,Close Price,Open Price,High Price,Low Price,Total Traded Quantity
498,"Oct 31, 2017",1033.04,1033.00,1041.00,1026.30,1520000.0
499,"Oct 30, 2017",1033.13,1029.16,1039.83,1022.33,2340000.0
500,"Oct 27, 2017",1033.67,1030.99,1063.62,1026.85,5180000.0
501,"Oct 26, 2017",991.42,998.47,1006.51,990.47,2370000.0
502,"Oct 25, 2017",991.46,986.27,994.43,977.72,1530000.0

In [26]:
df.describe()

,Close Price,Open Price,High Price,Low Price,Total Traded Quantity
count,503.000000,503.000000,503.000000,503.000000,5.030000e+02
mean,1132.038767,1131.834433,1142.713996,1120.766163,1.795025e+06
std,70.086966,69.720548,68.474476,71.023314,8.503835e+05
min,984.670000,984.320000,994.430000,977.660000,6.682400e+05
25%,1073.645000,1073.960000,1084.985000,1062.375000,1.270000e+06
50%,1128.630000,1130.000000,1139.300000,1116.790000,1.580000e+06
75%,1189.915000,1188.000000,1199.090000,1174.925000,2.030000e+06
max,1296.200000,1289.120000,1296.970000,1271.710000,6.660000e+06

# Problem Statement 1.2

 Calculate the maximum, minimum and mean price for the last 90 days. (price=Closing Price unless stated otherwise)

In [27]:
df.head(90)['Close Price'].max()

1259.11

In [28]:
df.head(90)['Close Price'].min()

1076.63

In [29]:
df.head(90)['Close Price'].mean()

1184.4741111111114

# Problem Statement 1.3

 Analyse the data types for each column of the dataframe. Pandas knows how to deal with dates in an intelligent manner. But to make use of Pandas functionality for dates, you need to ensure that the column is of type 'datetime64(ns)'. Change the date column from 'object' type to 'datetime64(ns)' for future convenience. See what happens if you subtract the minimum value of the date column from the maximum value.

In [30]:
df['Date'] = pd.to_datetime(df['Date'])
df['Date'].dtype

dtype('<M8[ns]')

In [31]:
df['Date'].max()-df['Date'].min()

Timedelta('729 days 00:00:00')

# Problem Statement 1.4

In a separate array , calculate the monthwise VWAP (Volume Weighted Average Price ) of the stock. ( VWAP = sum(price*volume)/sum(volume) ) To know more about VWAP , visit - VWAP definition {Hint : Create a new dataframe column ‘Month’. The values for this column can be derived from the ‘Date” column by using appropriate pandas functions. Similarly, create a column ‘Year’ and initialize it. Then use the 'groupby()' function by month and year. Finally, calculate the vwap value for each month (i.e. for each group created).

In [32]:
df['Month'] = pd.DatetimeIndex(df['Date']).month
df['Year'] = pd.DatetimeIndex(df['Date']).year
df['VWAP'] = (df['Close Price'] * df['Total Traded Quantity']).cumsum() / df['Total Traded Quantity'].fillna(0).cumsum()
df_vwap = df[['Month','Year','VWAP']]
group = df_vwap.groupby(['Month','Year'])
group.first()

                   VWAP
Month Year
1     2018  1132.194457
      2019  1169.772915
2     2018  1134.954233
      2019  1175.613996
3     2018  1138.321466
      2019  1174.467549
4     2018  1146.112859
      2019  1165.413291
5     2018  1150.429520
      2019  1165.119584
6     2018  1150.715115
      2019  1192.301354
7     2018  1145.862029
      2019  1206.415784
8     2018  1139.275360
      2019  1221.366974
9     2018  1135.524235
      2019  1222.652706
10    2017  1126.900460
      2018  1138.380187
      2019  1259.110000
11    2017  1129.484745
      2018  1146.194051
12    2017  1132.397874
      2018  1159.719337

# Problem Statement 1.5

 Write a function to calculate the average price over the last N days of the stock price data where N is a user defined parameter. Write a second function to calculate the profit/loss percentage over the last N days. Calculate the average price AND the profit/loss percentages over the course of last - 1 week, 2 weeks, 1 month, 3 months, 6 months and 1 year. {Note : Profit/Loss percentage between N days is the percentage change between the closing prices of the 2 days }

In [35]:
col = df.loc[: , "Close Price":"Low Price"]
df['Average Price'] = col.mean(axis=1)

In [40]:
def avg_price(N):
    return (df['Average Price'].head(N).sum())/N
print("Average prices for last N days are as follows:")
print("Last 1 week",avg_price(5))
print("Last 2 weeks",avg_price(10))
print("Last 1 month",avg_price(20))
print("Last 3 months",avg_price(60))
print("Last 6 months",avg_price(120))
print("Last 1 year",avg_price(240))
print("Profit/Loss % for N days are as follows:")
def prof_loss(N):
    difference = (df['Close Price'].head(N).iloc[N-1] - df['Close Price'].head(N).iloc[0])
    if difference < 0 :
        loss = -(difference)
        loss_percen = (loss/df['Close Price'].head(N).iloc[N-1])*100
        return loss_percen
    if difference > 0 :
        profit = difference
        profit_percen = (profit/df['Close Price'].head(N).iloc[N-1])*100
        return profit_percen
print("Loss/Profit percentage for last N days are as follows:")
print("Last 1 week",prof_loss(5))
print("Last 2 weeks",prof_loss(10))
print("Last 1 month",prof_loss(20))
print("Last 3 months",prof_loss(60))
print("Last 6 months",prof_loss(120))
print("Last 1 year",prof_loss(240))

Average prices for last N days are as follows:
Last 1 week 1249.3825000000002
Last 2 weeks 1241.65825
Last 1 month 1223.5223749999998
Last 3 months 1207.3361250000003
Last 6 months 1168.0438124999998
Last 1 year 1147.2410416666667
Profit/Loss % for N days are as follows:
Loss/Profit percentage for last N days are as follows:
Last 1 week 1.1812826962174698
Last 2 weeks 3.5699303287790562
Last 1 month 2.7048411436029083
Last 3 months 3.905824489593815
Last 6 months 6.807424121609013
Last 1 year 16.90683552765965

# Problem Statement 1.6

 Add a column 'Day_Perc_Change' where the values are the daily change in percentages i.e. the percentage change between 2 consecutive day's closing prices. Instead of using the basic mathematical formula for computing the same, use 'pct_change()' function provided by Pandas for dataframes. You will note that the first entry of the column will have a ‘Nan’ value. Why does this happen? Either remove the first row, or set the entry to 0 before proceeding.

In [41]:
df['Day_Perc_Change'] = df['Close Price'].pct_change().fillna(0)
df

,Date,Close Price,Open Price,High Price,Low Price,Total Traded Quantity,Month,Year,VWAP,Average Price,Day_Perc_Change
0,2019-10-24,1259.11,1259.11,1262.90,1252.35,1010000.0,10,2019,1259.110000,1258.3675,0.000000
1,2019-10-23,1257.63,1240.21,1258.04,1240.21,1180000.0,10,2019,1258.312557,1249.0225,-0.001175
2,2019-10-22,1241.20,1244.48,1248.73,1239.85,1280000.0,10,2019,1252.000144,1243.5650,-0.013064
3,2019-10-21,1244.28,1248.70,1253.51,1239.99,1030000.0,10,2019,1250.233089,1246.6200,0.002481
4,2019-10-18,1244.41,1254.69,1258.11,1240.14,1580000.0,10,2019,1248.719852,1249.3375,0.000104
5,2019-10-17,1252.80,1251.40,1263.75,1249.87,1060000.0,10,2019,1249.325588,1254.4550,0.006742
6,2019-10-16,1243.00,1241.81,1254.19,1238.53,1150000.0,10,2019,1248.448094,1244.3825,-0.007822
7,2019-10-15,1242.24,1221.50,1247.12,1220.92,1530000.0,10,2019,1247.480845,1232.9450,-0.000611
8,2019-10-14,1217.77,1213.89,1225.88,1211.88,683930.0,10,2019,1245.546318,1217.3550,-0.019698
9,2019-10-11,1215.71,1224.03,1228.75,1213.64,1130000.0,10,2019,1242.648326,1220.5325,-0.001692
10,2019-10-10,1209.47,1198.60,1215.62,1197.86,668240.0,10,2019,1240.846116,1205.3875,-0.005133
11,2019-10-09,1202.40,1201.33,1208.46,1198.12,813220.0,10,2019,1238.462264,1202.5775,-0.005846
12,2019-10-08,1190.13,1198.77,1206.87,1189.48,1030000.0,10,2019,1234.942939,1196.3125,-0.010205
13,2019-10-07,1208.25,1207.00,1218.91,1204.36,879020.0,10,2019,1233.381238,1209.6300,0.015225
14,2019-10-04,1210.96,1194.29,1212.46,1190.97,1230000.0,10,2019,1231.684584,1202.1700,0.002243
15,2019-10-03,1189.43,1183.34,1191.00,1163.14,1470000.0,10,2019,1228.180138,1181.7275,-0.017779
16,2019-10-02,1177.92,1196.50,1198.76,1172.63,1670000.0,10,2019,1223.852374,1186.4525,-0.009677
17,2019-10-01,1206.00,1222.49,1232.86,1205.55,1280000.0,10,2019,1222.747092,1216.7250,0.023839
18,2019-09-30,1221.14,1220.60,1227.40,1213.42,1290000.0,9,2019,1222.652706,1220.6400,0.012554
19,2019-09-27,1225.95,1242.83,1244.99,1215.20,1720000.0,9,2019,1222.892160,1232.2425,0.003939
20,2019-09-26,1242.29,1242.14,1244.67,1231.82,1170000.0,9,2019,1223.805297,1240.2300,0.013328
21,2019-09-25,1245.94,1216.01,1248.02,1209.20,1360000.0,9,2019,1224.953642,1229.7925,0.002938
22,2019-09-24,1218.33,1240.00,1247.11,1210.64,1840000.0,9,2019,1224.519219,1229.0200,-0.022160
23,2019-09-23,1234.69,1226.57,1239.68,1223.78,1200000.0,9,2019,1224.936419,1231.1800,0.013428
24,2019-09-20,1229.84,1233.64,1242.80,1223.58,1940000.0,9,2019,1225.241375,1232.4650,-0.003928
25,2019-09-19,1238.75,1232.32,1244.34,1232.31,847000.0,9,2019,1225.598470,1236.9300,0.007245
26,2019-09-18,1232.65,1230.24,1236.24,1216.47,892790.0,9,2019,1225.789625,1228.9000,-0.004924
27,2019-09-17,1229.88,1231.63,1235.00,1223.35,1050000.0,9,2019,1225.916004,1229.9650,-0.002247
28,2019-09-16,1231.63,1230.44,1239.02,1225.19,1410000.0,9,2019,1226.143632,1231.5700,0.001423
29,2019-09-13,1240.03,1232.11,1241.05,1227.08,1180000.0,9,2019,1226.591651,1235.0675,0.006820
...,...,...,...,...,...,...,...,...,...,...,...
473,2017-12-06,1032.72,1016.52,1039.58,1015.31,1440000.0,12,2017,1130.478017,1026.0325,-0.011344
474,2017-12-05,1019.60,1010.99,1036.68,1002.32,1950000.0,12,2017,1130.225862,1017.3975,-0.012704
475,2017-12-04,1011.87,1027.80,1031.34,1009.22,1940000.0,12,2017,1129.958685,1020.0575,-0.007581
476,2017-12-01,1025.07,1030.41,1037.24,1016.90,1890000.0,12,2017,1129.728518,1027.4050,0.013045
477,2017-11-30,1036.17,1039.94,1044.14,1030.07,2250000.0,11,2017,1129.484745,1037.5800,0.010829
478,2017-11-29,1037.38,1056.18,1058.77,1029.65,2790000.0,11,2017,1129.188122,1045.4950,0.001168
479,2017-11-28,1063.29,1073.99,1080.00,1054.54,1820000.0,11,2017,1129.049972,1067.9550,0.024976
480,2017-11-27,1072.01,1058.57,1073.04,1054.77,1770000.0,11,2017,1128.933914,1064.5975,0.008201
481,2017-11-24,1056.52,1054.39,1060.07,1051.92,825370.0,11,2017,1128.865273,1055.7250,-0.014449
482,2017-11-22,1051.92,1051.16,1055.43,1047.25,726900.0,11,2017,1128.801093,1051.4400,-0.004354
483,2017-11-21,1050.30,1040.04,1050.39,1039.14,1110000.0,11,2017,1128.701232,1044.9675,-0.001540
484,2017-11-20,1034.66,1036.00,1038.69,1032.67,876320.0,11,2017,1128.606882,1035.5050,-0.014891
485,2017-11-17,1035.89,1049.80,1051.00,1033.73,1340000.0,11,2017,1128.464860,1042.6050,0.001189
486,2017-11-16,1048.47,1038.75,1051.76,1038.00,1190000.0,11,2017,1128.356189,1044.2450,0.012144
487,2017-11-15,1036.41,1035.00,1039.63,1030.76,905260.0,11,2017,1128.261268,1035.4500,-0.011502
488,2017-11-14,1041.64,1037.72,1042.30,1029.33,1050000.0,11,2017,1128.157670,1037.7475,0.005046
489,2017-11-13,1041.20,1040.80,1048.74,1039.26,940720.0,11,2017,1128.064594,1042.5000,-0.000422
490,2017-11-10,1044.15,1043.87,1046.63,1041.22,972130.0,11,2017,1127.971879,1043.9675,0.002833
491,2017-11-09,1047.72,1048.00,1050.88,1035.85,1790000.0,11,2017,1127.808943,1045.6125,0.003419
492,2017-11-08,1058.29,1050.05,1062.69,1047.05,1210000.0,11,2017,1127.713664,1054.5200,0.010089
493,2017-11-07,1052.39,1049.65,1053.41,1043.00,1310000.0,11,2017,1127.602062,1049.6125,-0.005575
494,2017-11-06,1042.68,1049.10,1052.59,1042.00,914750.0,11,2017,1127.514293,1046.5925,-0.009227
495,2017-11-03,1049.99,1042.75,1050.66,1037.65,1390000.0,11,2017,1127.392733,1045.2625,0.007011
496,2017-11-02,1042.97,1039.99,1045.52,1028.66,1330000.0,11,2017,1127.266260,1039.2850,-0.006686
497,2017-11-01,1042.60,1036.32,1047.86,1034.00,2160000.0,11,2017,1127.060768,1040.1950,-0.000355
498,2017-10-31,1033.04,1033.00,1041.00,1026.30,1520000.0,10,2017,1126.900460,1033.3350,-0.009169
499,2017-10-30,1033.13,1029.16,1039.83,1022.33,2340000.0,10,2017,1126.654970,1031.1125,0.000087
500,2017-10-27,1033.67,1030.99,1063.62,1026.85,5180000.0,10,2017,1126.119193,1038.7825,0.000523
501,2017-10-26,991.42,998.47,1006.51,990.47,2370000.0,10,2017,1125.765023,996.7175,-0.040874
502,2017-10-25,991.46,986.27,994.43,977.72,1530000.0,10,2017,1125.537437,987.4700,0.000040

# Problem Statement 1.7

 Add another column 'Trend' whose values are: 'Slight or No change' for 'Day_Perc_Change' in between -0.5 and 0.5 'Slight positive' for 'Day_Perc_Change' in between 0.5 and 1 'Slight negative' for 'Day_Perc_Change' in between -0.5 and -1 'Positive' for 'Day_Perc_Change' in between 1 and 3 'Negative' for 'Day_Perc_Change' in between -1 and -3 'Among top gainers' for 'Day_Perc_Change' in between 3 and 7 'Among top losers' for 'Day_Perc_Change' in between -3 and -7 'Bull run' for 'Day_Perc_Change' >7 'Bear drop' for 'Day_Perc_Change' <-7

In [42]:

if ((df['Day_Perc_Change'] >= -0.5) & (df['Day_Perc_Change'] <= 0.5)).all():
    df['Trend'] = 'Slight or No change'
if ((df['Day_Perc_Change'] >= 0.5) & (df['Day_Perc_Change'] <= 1)).all():
    df['Trend'] = 'Slight positive'
if ((df['Day_Perc_Change'] <= -0.5) & (df['Day_Perc_Change'] >= -1)).all():
    df['Trend'] = 'Slight negative'
if ((df['Day_Perc_Change'] >= 1) & (df['Day_Perc_Change'] <= 3)).all():
    df['Trend'] = 'Positive' 
if ((df['Day_Perc_Change'] <= -1) & (df['Day_Perc_Change'] >= -3)).all():
    df['Trend'] = 'Negative'
if ((df['Day_Perc_Change'] >= 3) & (df['Day_Perc_Change'] <= 7)).all():
    df['Trend'] = 'Among top gainers'
if ((df['Day_Perc_Change'] <= -3) & (df['Day_Perc_Change'] >= -7)).all():
    df['Trend'] = 'Among top losers'
if (df['Day_Perc_Change'] > 7).all():
    df['Trend'] = 'Bull run' 
if (df['Day_Perc_Change'] < -7).all():
    df['Trend'] = 'Bear drop' 
df

,Date,Close Price,Open Price,High Price,Low Price,Total Traded Quantity,Month,Year,VWAP,Average Price,Day_Perc_Change,Trend
0,2019-10-24,1259.11,1259.11,1262.90,1252.35,1010000.0,10,2019,1259.110000,1258.3675,0.000000,Slight or No change
1,2019-10-23,1257.63,1240.21,1258.04,1240.21,1180000.0,10,2019,1258.312557,1249.0225,-0.001175,Slight or No change
2,2019-10-22,1241.20,1244.48,1248.73,1239.85,1280000.0,10,2019,1252.000144,1243.5650,-0.013064,Slight or No change
3,2019-10-21,1244.28,1248.70,1253.51,1239.99,1030000.0,10,2019,1250.233089,1246.6200,0.002481,Slight or No change
4,2019-10-18,1244.41,1254.69,1258.11,1240.14,1580000.0,10,2019,1248.719852,1249.3375,0.000104,Slight or No change
5,2019-10-17,1252.80,1251.40,1263.75,1249.87,1060000.0,10,2019,1249.325588,1254.4550,0.006742,Slight or No change
6,2019-10-16,1243.00,1241.81,1254.19,1238.53,1150000.0,10,2019,1248.448094,1244.3825,-0.007822,Slight or No change
7,2019-10-15,1242.24,1221.50,1247.12,1220.92,1530000.0,10,2019,1247.480845,1232.9450,-0.000611,Slight or No change
8,2019-10-14,1217.77,1213.89,1225.88,1211.88,683930.0,10,2019,1245.546318,1217.3550,-0.019698,Slight or No change
9,2019-10-11,1215.71,1224.03,1228.75,1213.64,1130000.0,10,2019,1242.648326,1220.5325,-0.001692,Slight or No change
10,2019-10-10,1209.47,1198.60,1215.62,1197.86,668240.0,10,2019,1240.846116,1205.3875,-0.005133,Slight or No change
11,2019-10-09,1202.40,1201.33,1208.46,1198.12,813220.0,10,2019,1238.462264,1202.5775,-0.005846,Slight or No change
12,2019-10-08,1190.13,1198.77,1206.87,1189.48,1030000.0,10,2019,1234.942939,1196.3125,-0.010205,Slight or No change
13,2019-10-07,1208.25,1207.00,1218.91,1204.36,879020.0,10,2019,1233.381238,1209.6300,0.015225,Slight or No change
14,2019-10-04,1210.96,1194.29,1212.46,1190.97,1230000.0,10,2019,1231.684584,1202.1700,0.002243,Slight or No change
15,2019-10-03,1189.43,1183.34,1191.00,1163.14,1470000.0,10,2019,1228.180138,1181.7275,-0.017779,Slight or No change
16,2019-10-02,1177.92,1196.50,1198.76,1172.63,1670000.0,10,2019,1223.852374,1186.4525,-0.009677,Slight or No change
17,2019-10-01,1206.00,1222.49,1232.86,1205.55,1280000.0,10,2019,1222.747092,1216.7250,0.023839,Slight or No change
18,2019-09-30,1221.14,1220.60,1227.40,1213.42,1290000.0,9,2019,1222.652706,1220.6400,0.012554,Slight or No change
19,2019-09-27,1225.95,1242.83,1244.99,1215.20,1720000.0,9,2019,1222.892160,1232.2425,0.003939,Slight or No change
20,2019-09-26,1242.29,1242.14,1244.67,1231.82,1170000.0,9,2019,1223.805297,1240.2300,0.013328,Slight or No change
21,2019-09-25,1245.94,1216.01,1248.02,1209.20,1360000.0,9,2019,1224.953642,1229.7925,0.002938,Slight or No change
22,2019-09-24,1218.33,1240.00,1247.11,1210.64,1840000.0,9,2019,1224.519219,1229.0200,-0.022160,Slight or No change
23,2019-09-23,1234.69,1226.57,1239.68,1223.78,1200000.0,9,2019,1224.936419,1231.1800,0.013428,Slight or No change
24,2019-09-20,1229.84,1233.64,1242.80,1223.58,1940000.0,9,2019,1225.241375,1232.4650,-0.003928,Slight or No change
25,2019-09-19,1238.75,1232.32,1244.34,1232.31,847000.0,9,2019,1225.598470,1236.9300,0.007245,Slight or No change
26,2019-09-18,1232.65,1230.24,1236.24,1216.47,892790.0,9,2019,1225.789625,1228.9000,-0.004924,Slight or No change
27,2019-09-17,1229.88,1231.63,1235.00,1223.35,1050000.0,9,2019,1225.916004,1229.9650,-0.002247,Slight or No change
28,2019-09-16,1231.63,1230.44,1239.02,1225.19,1410000.0,9,2019,1226.143632,1231.5700,0.001423,Slight or No change
29,2019-09-13,1240.03,1232.11,1241.05,1227.08,1180000.0,9,2019,1226.591651,1235.0675,0.006820,Slight or No change
...,...,...,...,...,...,...,...,...,...,...,...,...
473,2017-12-06,1032.72,1016.52,1039.58,1015.31,1440000.0,12,2017,1130.478017,1026.0325,-0.011344,Slight or No change
474,2017-12-05,1019.60,1010.99,1036.68,1002.32,1950000.0,12,2017,1130.225862,1017.3975,-0.012704,Slight or No change
475,2017-12-04,1011.87,1027.80,1031.34,1009.22,1940000.0,12,2017,1129.958685,1020.0575,-0.007581,Slight or No change
476,2017-12-01,1025.07,1030.41,1037.24,1016.90,1890000.0,12,2017,1129.728518,1027.4050,0.013045,Slight or No change
477,2017-11-30,1036.17,1039.94,1044.14,1030.07,2250000.0,11,2017,1129.484745,1037.5800,0.010829,Slight or No change
478,2017-11-29,1037.38,1056.18,1058.77,1029.65,2790000.0,11,2017,1129.188122,1045.4950,0.001168,Slight or No change
479,2017-11-28,1063.29,1073.99,1080.00,1054.54,1820000.0,11,2017,1129.049972,1067.9550,0.024976,Slight or No change
480,2017-11-27,1072.01,1058.57,1073.04,1054.77,1770000.0,11,2017,1128.933914,1064.5975,0.008201,Slight or No change
481,2017-11-24,1056.52,1054.39,1060.07,1051.92,825370.0,11,2017,1128.865273,1055.7250,-0.014449,Slight or No change
482,2017-11-22,1051.92,1051.16,1055.43,1047.25,726900.0,11,2017,1128.801093,1051.4400,-0.004354,Slight or No change
483,2017-11-21,1050.30,1040.04,1050.39,1039.14,1110000.0,11,2017,1128.701232,1044.9675,-0.001540,Slight or No change
484,2017-11-20,1034.66,1036.00,1038.69,1032.67,876320.0,11,2017,1128.606882,1035.5050,-0.014891,Slight or No change
485,2017-11-17,1035.89,1049.80,1051.00,1033.73,1340000.0,11,2017,1128.464860,1042.6050,0.001189,Slight or No change
486,2017-11-16,1048.47,1038.75,1051.76,1038.00,1190000.0,11,2017,1128.356189,1044.2450,0.012144,Slight or No change
487,2017-11-15,1036.41,1035.00,1039.63,1030.76,905260.0,11,2017,1128.261268,1035.4500,-0.011502,Slight or No change
488,2017-11-14,1041.64,1037.72,1042.30,1029.33,1050000.0,11,2017,1128.157670,1037.7475,0.005046,Slight or No change
489,2017-11-13,1041.20,1040.80,1048.74,1039.26,940720.0,11,2017,1128.064594,1042.5000,-0.000422,Slight or No change
490,2017-11-10,1044.15,1043.87,1046.63,1041.22,972130.0,11,2017,1127.971879,1043.9675,0.002833,Slight or No change
491,2017-11-09,1047.72,1048.00,1050.88,1035.85,1790000.0,11,2017,1127.808943,1045.6125,0.003419,Slight or No change
492,2017-11-08,1058.29,1050.05,1062.69,1047.05,1210000.0,11,2017,1127.713664,1054.5200,0.010089,Slight or No change
493,2017-11-07,1052.39,1049.65,1053.41,1043.00,1310000.0,11,2017,1127.602062,1049.6125,-0.005575,Slight or No change
494,2017-11-06,1042.68,1049.10,1052.59,1042.00,914750.0,11,2017,1127.514293,1046.5925,-0.009227,Slight or No change
495,2017-11-03,1049.99,1042.75,1050.66,1037.65,1390000.0,11,2017,1127.392733,1045.2625,0.007011,Slight or No change
496,2017-11-02,1042.97,1039.99,1045.52,1028.66,1330000.0,11,2017,1127.266260,1039.2850,-0.006686,Slight or No change
497,2017-11-01,1042.60,1036.32,1047.86,1034.00,2160000.0,11,2017,1127.060768,1040.1950,-0.000355,Slight or No change
498,2017-10-31,1033.04,1033.00,1041.00,1026.30,1520000.0,10,2017,1126.900460,1033.3350,-0.009169,Slight or No change
499,2017-10-30,1033.13,1029.16,1039.83,1022.33,2340000.0,10,2017,1126.654970,1031.1125,0.000087,Slight or No change
500,2017-10-27,1033.67,1030.99,1063.62,1026.85,5180000.0,10,2017,1126.119193,1038.7825,0.000523,Slight or No change
501,2017-10-26,991.42,998.47,1006.51,990.47,2370000.0,10,2017,1125.765023,996.7175,-0.040874,Slight or No change
502,2017-10-25,991.46,986.27,994.43,977.72,1530000.0,10,2017,1125.537437,987.4700,0.000040,Slight or No change

# Problem Statement 1.8

 Find the average and median values of the column 'Total Traded Quantity' for each of the types of 'Trend'. {Hint : use 'groupby()' on the 'Trend' column and then calculate the average and median values of the column 'Total Traded Quantity'}

In [44]:
df.groupby(df.Trend).mean()['Total Traded Quantity']
df.groupby(df.Trend).median()['Total Traded Quantity']

Trend
Slight or No change    1580000.0
Name: Total Traded Quantity, dtype: float64

# Problem Statement 1.9
SAVE the dataframe with the additional columns computed as a csv file week2.csv. In Module 2, you are going to get familiar with matplotlib, the python module which is used to visualize data.

In [48]:
df.to_csv('week2.csv')